apiVersion: apps/v1
kind: Deployment
metadata:
  name: rns
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rns
  template:
    metadata:
      labels:
        app: rns
    spec:
      containers:
      - image: 324898396996.dkr.ecr.ap-southeast-2.amazonaws.com/rns:latest
        name: rns
        ports:
        - containerPort: 8095
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1024Mi"
        readinessProbe:
          httpGet:
            path: /RoadNameWS/getAllLGAs
            port: 8095
          initialDelaySeconds: 120
          periodSeconds: 60
